api:
  url: "https://openexchangerates.org/api/latest.json"
  key: "da7046fc817e4b9794df828d24c80027"
db:
  conn: "http://host.docker.internal:8000"
  table: "conversion_rates"
kafka:
  brokers: "kafka:9092"
  topic: "currency_updates"