version: '3'
services:
  polling-service:
    build: .
    container_name: polling-service
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
    volumes:
      - ./config.yaml:/root/config.yaml
    ports:
      - "8082:8082"
    networks:
      - kafka_network

networks:
  kafka_network:
    external: true